const CACHE_NAME='voicetrader-shell-v0.9-forward-epoch-v0.10-live-forward-v0.11-human-knowledge-v0.12-knowledge-attribution-v0.13-human-playbook-v0.14-candidate-tournament-v0.15-knowledge-forward-v0.16-autonomous-collector-v0.17-champion-promotion-v0.18-evidence-replay-audit';
const APP_SHELL=[
  './','./index.html','./styles.css','./ui-hotfix.css','./ui-layout.css','./ui-viewport.css','./research-evaluation.css','./walk-forward.css','./forward-demo.css','./live-forward.css','./human-knowledge.css','./human-playbook.css','./candidate-tournament.css','./knowledge-forward.css','./champion-promotion.css','./knowledge-forward-audit.css','./manifest.webmanifest',
  './src/app.js','./src/config.js','./src/pwa.js',
  './src/data/market-data-provider.js','./src/research/decision-event-log.js','./src/research/counterfactual-shadow.js','./src/research/baseline-runner.js','./src/research/null-market-runner.js','./src/research/strategy-registry.js','./src/research/challenger-runner.js','./src/research/walk-forward-runner.js','./src/research/walk-forward-state.js','./src/research/walk-forward-ui.js','./src/research/forward-epoch.js','./src/research/forward-demo-runner.js','./src/research/forward-evidence-store.js','./src/research/forward-demo-state.js','./src/research/forward-demo-ui.js','./src/research/knowledge-shadow-runner.js','./src/research/knowledge-attribution-runner.js','./src/research/knowledge-state.js','./src/research/knowledge-ui.js','./src/research/knowledge-attribution-ui.js','./src/research/playbook-shadow-runner.js','./src/research/playbook-attribution-runner.js','./src/research/playbook-walk-forward.js','./src/research/playbook-state.js','./src/research/playbook-ui.js','./src/research/knowledge-candidate-registry.js','./src/research/knowledge-candidate-tournament.js','./src/research/knowledge-candidate-state.js','./src/research/knowledge-candidate-ui.js','./src/research/research-cost-model.js','./src/research/knowledge-forward-epoch.js','./src/research/knowledge-forward-runner.js','./src/research/knowledge-forward-store.js','./src/research/knowledge-forward-state.js','./src/research/knowledge-forward-remote.js','./src/research/knowledge-forward-ui.js','./src/research/knowledge-forward-replay-audit.js','./src/research/knowledge-forward-replay-audit-state.js','./src/research/knowledge-forward-replay-audit-ui.js','./src/research/champion-promotion-protocol.js','./src/research/champion-promotion-evaluator.js','./src/research/champion-promotion-state.js','./src/research/champion-promotion-replay-gate.js','./src/research/champion-promotion-ui.js','./src/research/research-export.js','./src/research/research-evaluation-ui.js',
  './src/live/live-forward-paper.js','./src/live/live-forward-store.js','./src/live/live-forward-ui.js',
  './src/knowledge/knowledge-registry.js','./src/knowledge/knowledge-indicators.js','./src/knowledge/expert-library.js','./src/knowledge/human-knowledge-engine.js','./src/knowledge/playbook-registry.js','./src/knowledge/playbook-features.js','./src/knowledge/playbook-engine.js',
  './src/engine/indicators.js','./src/engine/experts.js','./src/engine/decision-policy.js','./src/engine/shadow-engine.js','./src/engine/ai-provider.js','./src/engine/execution-engine.js',
  './assets/icons/icon-192.png','./assets/icons/icon-512.png','./assets/icons/icon-maskable-512.png','./assets/icons/apple-touch-icon.png'
];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(APP_SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{if(e.request.method!=='GET'||new URL(e.request.url).origin!==self.location.origin)return;if(e.request.mode==='navigate'){e.respondWith(fetch(e.request,{cache:'no-store'}).catch(()=>caches.match('./index.html')));return}e.respondWith(caches.match(e.request).then(c=>c||fetch(e.request)))});
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});
