param([string]$DataRoot='X:\XVoiceTraderData',[string]$OverlayRef='',[int]$HealthMaxAgeMs=90000)
$ErrorActionPreference='Stop';$Repo='TAMAFIT/voicetrader-pwa';$RuntimeRoot=Join-Path $DataRoot 'runtime\voicetrader-local-node';$V084=Join-Path $DataRoot 'state\local-edge-lab-v084-config.json';$V085=Join-Path $DataRoot 'state\local-edge-lab-v085-config.json';$Base=Join-Path $DataRoot 'state\local-node-config.json';$Stamp=(Get-Date).ToUniversalTime().ToString('yyyyMMdd-HHmmss');$Stage=Join-Path $DataRoot "staging\voicetrader-v086-$Stamp";$Backup=Join-Path $DataRoot "runtime-backups\voicetrader-before-v086-overlay-$Stamp";$ReceiptPath=Join-Path $DataRoot 'state\local-edge-lab-v086-config.json';$TaskName='VoiceTrader-LocalNode-SoakCertifier'
function Test-Administrator{$i=[Security.Principal.WindowsIdentity]::GetCurrent();$p=[Security.Principal.WindowsPrincipal]::new($i);$p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)}
function Assert-ExactCommit([string]$Ref){if($Ref -notmatch '^[0-9a-f]{40}$'){throw 'OverlayRef must be exact 40-hex commit'}}
function RuntimePath([string]$RelativePath){Join-Path $RuntimeRoot ($RelativePath -replace '/','\')}
function StagedPath([string]$RelativePath){Join-Path $Stage ($RelativePath -replace '/','\')}
function Download-Overlay([string]$RelativePath){$d=StagedPath $RelativePath;New-Item -ItemType Directory -Force -Path (Split-Path $d -Parent)|Out-Null;Invoke-WebRequest -UseBasicParsing -Uri "https://raw.githubusercontent.com/$Repo/$OverlayRef/$RelativePath" -OutFile $d;if(-not(Test-Path $d)-or(Get-Item $d).Length -le 0){throw "download failed: $RelativePath"}}
function Read-V084Health([string]$NodeExe){$x=& $NodeExe (RuntimePath 'scripts/local-node/v084-health-gate.mjs') --root $DataRoot --max-age-ms $HealthMaxAgeMs --json 2>$null;if($x){try{return ($x -join "`n")|ConvertFrom-Json}catch{}};return $null}
function Save-JsonAtomic([string]$FilePath,$Value){$parent=Split-Path $FilePath -Parent;if([string]::IsNullOrWhiteSpace($parent)){throw "Atomic JSON parent path missing: $FilePath"};New-Item -ItemType Directory -Force -Path $parent|Out-Null;$tmp="$FilePath.tmp";$Value|ConvertTo-Json -Depth 10|Set-Content -Encoding UTF8 -Path $tmp;Move-Item -Force $tmp $FilePath}
if(-not(Test-Administrator)){if(-not $PSCommandPath){throw 'Save as .ps1 before running'};$a=@('-NoProfile','-ExecutionPolicy','Bypass','-File',('"{0}"' -f $PSCommandPath),'-DataRoot',('"{0}"' -f $DataRoot),'-OverlayRef',$OverlayRef,'-HealthMaxAgeMs',$HealthMaxAgeMs);$p=Start-Process powershell.exe -Verb RunAs -Wait -PassThru -ArgumentList $a;exit $p.ExitCode}
Assert-ExactCommit $OverlayRef;if(-not(Test-Path $V084)){throw 'v0.84 receipt missing'};if(-not(Test-Path $V085)){throw 'v0.85 receipt missing'};$c84=Get-Content -Raw $V084|ConvertFrom-Json;$c85=Get-Content -Raw $V085|ConvertFrom-Json;$b=Get-Content -Raw $Base|ConvertFrom-Json;$node=[string]$b.nodeExe;if(-not $node -or -not(Test-Path $node)){$cmd=Get-Command node.exe -ErrorAction SilentlyContinue;if(-not $cmd){throw 'Node.js missing'};$node=$cmd.Source};if([int](((& $node --version).Trim().TrimStart('v') -split '\.')[0]) -lt 22){throw 'Node 22+ required'};$h=Read-V084Health $node;if(-not $h -or $h.status -ne 'PASS'){throw 'v0.84 live health must PASS before v0.86 overlay'}
$files=@('src/short-horizon/local-edge-lab-soak-certifier.js','scripts/local-node/v086-soak-certifier.mjs');$test='scripts/test-short-horizon-v086-soak-certification.mjs';$deps=@('src/short-horizon/local-edge-lab-v084-health.js','scripts/local-node/v084-health-gate.mjs');New-Item -ItemType Directory -Force -Path $Stage|Out-Null
try{foreach($x in @($files+$test)){Download-Overlay $x};foreach($x in $deps){$src=RuntimePath $x;$dst=StagedPath $x;if(-not(Test-Path $src)){throw "dependency missing: $x"};New-Item -ItemType Directory -Force -Path (Split-Path $dst -Parent)|Out-Null;Copy-Item $src $dst};foreach($x in $files){& $node --check (StagedPath $x);if($LASTEXITCODE -ne 0){throw "syntax failed: $x"}};& $node (StagedPath $test);if($LASTEXITCODE -ne 0){throw 'v0.86 regression failed'};if(Select-String -Path (StagedPath $files[0]),(StagedPath $files[1]) -Pattern 'blind-sealed|BlindReveal|orderSubmission:true|realMoneyRouting:true|cloudUploadEnabled:true' -Quiet){throw 'forbidden v0.86 surface'}}catch{Remove-Item -Recurse -Force $Stage -ErrorAction SilentlyContinue;throw}
$old=Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue;$xml=if($old){Export-ScheduledTask -TaskName $TaskName}else{$null};Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue;New-Item -ItemType Directory -Force -Path $Backup|Out-Null;$had=@{};foreach($x in $files){$d=RuntimePath $x;if(Test-Path $d){$had[$x]=$true;$q=Join-Path $Backup ($x -replace '/','\');New-Item -ItemType Directory -Force -Path (Split-Path $q -Parent)|Out-Null;Copy-Item $d $q}else{$had[$x]=$false}}
try{foreach($x in $files){$d=RuntimePath $x;New-Item -ItemType Directory -Force -Path (Split-Path $d -Parent)|Out-Null;Copy-Item -Force (StagedPath $x) $d};if(Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue){Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false};$worker=RuntimePath 'scripts/local-node/v086-soak-certifier.mjs';$action=New-ScheduledTaskAction -Execute $node -Argument ('"{0}" --root "{1}" --poll-ms 60000 --max-age-ms {2}' -f $worker,$DataRoot,$HealthMaxAgeMs) -WorkingDirectory $RuntimeRoot;$trigger=New-ScheduledTaskTrigger -AtStartup;$principal=New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest;$settings=New-ScheduledTaskSettingsSet -StartWhenAvailable -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew;Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Description 'VoiceTrader v0.86 24h operations soak certifier; no research outcome access'|Out-Null;Start-ScheduledTask -TaskName $TaskName;Start-Sleep -Seconds 3;$task=Get-ScheduledTask -TaskName $TaskName;if($task.State -eq 'Disabled'){throw 'v0.86 task disabled'};$after=Read-V084Health $node;if(-not $after -or $after.status -ne 'PASS'){throw 'v0.84 health regressed after v0.86 overlay'};$ReceiptRecord=[ordered]@{schemaVersion='voicetrader-local-edge-lab-v086-overlay';installedAt=(Get-Date).ToUniversalTime().ToString('o');baseRuntimeRef=[string]$c84.exactRuntimeRef;rebootOverlayRef=[string]$c85.overlayRef;soakOverlayRef=$OverlayRef;taskName=$TaskName;target='24_CONSECUTIVE_CERTIFIED_HOURS';blindResultsRead=$false;runtimePolicy=[ordered]@{googleCloudEnabled=$false;cloudUploadEnabled=$false;orderSubmission=$false;realMoneyRouting=$false};rollback=[ordered]@{backup=$Backup;priorTaskCaptured=[bool]$xml;dataDirectoriesPreserved=$true}};Save-JsonAtomic $ReceiptPath $ReceiptRecord}catch{Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue;Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue;foreach($x in $files){$d=RuntimePath $x;if($had[$x]){Copy-Item -Force (Join-Path $Backup ($x -replace '/','\')) $d}else{Remove-Item -Force $d -ErrorAction SilentlyContinue}};if($xml){Register-ScheduledTask -TaskName $TaskName -Xml $xml -Force|Out-Null;Start-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue};Remove-Item -Recurse -Force $Stage -ErrorAction SilentlyContinue;throw}
Remove-Item -Recurse -Force $Stage -ErrorAction SilentlyContinue;Write-Host 'v0.86 soak certifier installed. 24 consecutive certified hours are required for PROVEN_24H.'
